#!/bin/bash
source colors.sh
HOME=/home/gvalera
GIT=${HOME}/GIT
COLLECTOR=${GIT}/EG-Collector
TOOLS=${COLLECTOR}-Tools
HEIGHT=30
WIDTH=70
CHOICE_HEIGHT=25
BACKTITLE="Emtec Group Collector"
TITLE="Developer's Menu - Collector (${TOOLS})"
MENU="Choose one of the folowing options:"
OPTIONS=(   
            2 "Generate and Compile Source Code" 
            1 "GITLab Pull"
            a "GitLab Push"
            b "Collector              Source Up (Flask) DEV"
            e "Collector              Source Up (Flask) QA"
            f "Collector              Source Up (Flask) AAAA"
            c "Collector Nutanix PC 3 Source Up"
            d "Collector Services     Source Up"
            s "SQL Tools Menu"
            q "Quit"
        )
while true;
do

    CHOICE=$(   dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 > /dev/tty)
    clear
    case $CHOICE in
        1)
            git pull origin master
            ;;
        2)
            cd ${TOOLS}
            make
            cd ${COLLECTOR}
            ls -lh *.py
            python -m compileall collector*.py
            ;;
        a)
            timestamp=$(date +%Y%m%d-%H%M)
            git add .
            git commit -m "Update ${timestamp}"
            git push origin master
            ;;
        b)
            cd ${COLLECTOR}
            python ${COLLECTOR}/collector.py ${COLLECTOR}/collector-dev.ini FLASK
            ;;
        e)
            cd ${COLLECTOR}
            python ${COLLECTOR}/collector.py ${COLLECTOR}/collector-qa.ini FLASK
            ;;
        f)
            cd ${COLLECTOR}
            python ${COLLECTOR}/collector.py ${COLLECTOR}/collector-aaaa.ini FLASK
            ;;
        c)
            cd ${COLLECTOR}
	    python ${COLLECTOR}/collector_drv_nutanix.py ${COLLECTOR}/collector.ini Nutanix_1_PC_3
            ;;
        d)
            cd ${COLLECTOR}
	    python ${COLLECTOR}/collector_services.py ${COLLECTOR}/collector.ini Services
            ;;
        s)
            cd ${COLLECTOR}/sql
            ./menu
            ;;
        q)
            exit 0
    esac
    echo 
    echo -e ${bold}${yellow}"Pulse una tecla para continuar ..."${normal}
    read
done
