source /home/collector/bin/colors.sh
echo -e ${bold}${yellow}
echo Updating collector ...
echo Stopping collector service ...
sudo systemctl stop collector
echo Updating binary ...
cp /home/collector/dist/collector /home/collector/bin/collector
echo Start collector service ...
sudo systemctl start collector
echo -e ${green}Status of collector service:${normal}
sudo systemctl status collector
echo
