source /home/collector/bin/colors.sh
echo -e ${bold}${yellow}
echo Updating collector_services ...
echo Stopping collector_services service ...
sudo systemctl stop collector_services
echo Updating binary ...
cp /home/collector/dist/collector_services /home/collector/bin/collector_services
echo Start collector_services service ...
sudo systemctl start collector_services
echo -e ${green}Status of collector_services service:${normal}
sudo systemctl status collector_services
echo
