-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema collector_development
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `collector_development` ;

-- -----------------------------------------------------
-- Schema collector_development
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `collector_development` DEFAULT CHARACTER SET utf8 ;
USE `collector_development` ;

-- -----------------------------------------------------
-- Table `collector_development`.`Forms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collector_development`.`Forms` ;

CREATE TABLE IF NOT EXISTS `collector_development`.`Forms` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Table` VARCHAR(45) NOT NULL,
  `Field` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Null` VARCHAR(45) NULL,
  `Key` VARCHAR(45) NULL,
  `Default` VARCHAR(45) NULL,
  `Extra` VARCHAR(45) NULL,
  `Foreign_Key` VARCHAR(45) NULL,
  `Referenced_Table` VARCHAR(45) NULL,
  `Foreign_Field` VARCHAR(45) NULL,
  `Length` INT NULL,
  `Validation` TINYINT NULL,
  `Validation_Type` VARCHAR(45) NULL,
  `Validation_String` VARCHAR(128) NULL,
  `Caption_String` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collector_development`.`Tables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collector_development`.`Tables` ;

CREATE TABLE IF NOT EXISTS `collector_development`.`Tables` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Caption` VARCHAR(45) NULL,
  `Entity` VARCHAR(45) NULL,
  `Class_Name` VARCHAR(45) NULL,
  `Child_Table` VARCHAR(45) NULL,
  `Use_Pagination` TINYINT NULL,
  `Use_Children_Pagination` TINYINT NULL,
  `Generate_Form_One` TINYINT NULL,
  `Generate_Form_All` TINYINT NULL,
  `Generate_Form_Filter` TINYINT NULL,
  `Generate_Children` TINYINT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `collector_development`.`Forms`
-- -----------------------------------------------------
START TRANSACTION;
USE `collector_development`;
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (1, 'Charge_Items', 'CIT_Date', 'date', 'NO', 'PRI', '2018-01-01', '', 'NULL', 'NULL', 'NULL', 10, 1, 'FK', 'Required()', 'Date');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (2, 'Charge_Items', 'CIT_Is_Active', 'tinyint(4)', 'YES', '', '0', '', 'NULL', 'NULL', 'NULL', 4, NULL, 'NULL', 'NULL', 'Is Active');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (3, 'Charge_Items', 'CIT_Quantity', 'decimal(20,6)', 'NO', '', '0.000000', '', 'NULL', 'NULL', 'NULL', 20, NULL, 'NULL', 'NULL', 'Quantity');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (4, 'Charge_Items', 'CIT_Status', 'int(11)', 'YES', '', '0', '', 'CIT_Status', 'CIT_Statuses', 'Value', 45, 1, 'FK', 'Required()', 'Status');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (5, 'Charge_Items', 'CIT_Time', 'time', 'NO', 'PRI', '00:00:00', '', 'NULL', 'NULL', 'NULL', 8, 1, 'FK', 'Required()', 'Time');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (6, 'Charge_Items', 'CU_Id', 'int(11)', 'NO', 'PRI', '0', '', 'CU_Id', 'Charge_Units', 'CU_Description', 11, 1, 'FK', 'Required()', 'Charge Unit Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (7, 'Charge_Units', 'CC_Id', 'int(11)', 'NO', 'MUL', '0', '', 'CC_Id', 'Cost_Centers', 'CC_Description', 11, 1, 'FK', 'Required()', 'Cost Center Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (8, 'Charge_Units', 'CI_Id', 'int(11)', 'NO', 'MUL', '0', '', 'CI_Id', 'Configuration_Items', 'CI_Name', 11, 1, 'FK', 'Required()', 'Configuration Item Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (9, 'Charge_Units', 'CU_Description', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Description');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (10, 'Charge_Units', 'CU_Id', 'int(11)', 'NO', 'PRI', 'NULL', 'auto_increment', 'NULL', 'NULL', 'NULL', 11, 1, 'FK', 'Required()', 'Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (11, 'Charge_Units', 'CU_Is_Always_Billeable', 'tinyint(4)', 'YES', '', '0', '', 'NULL', 'NULL', 'NULL', 4, NULL, 'NULL', 'NULL', 'Is Always Billeable');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (12, 'Charge_Units', 'CU_Is_Billeable', 'tinyint(4)', 'YES', '', '0', '', 'NULL', 'NULL', 'NULL', 4, NULL, 'NULL', 'NULL', 'Is Billeable');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (13, 'Charge_Units', 'CU_Operation', 'varchar(10)', 'YES', '', 'NONE', '', 'CU_Operation', 'CU_Operations', 'Value', 45, 1, 'FK', 'Required()', 'Conversion Operation');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (14, 'Charge_Units', 'CU_Quantity', 'decimal(20,6)', 'YES', '', '0.000000', '', 'NULL', 'NULL', 'NULL', 20, NULL, 'NULL', 'NULL', 'Default Quantity');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (15, 'Charge_Units', 'CU_UUID', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'UUID');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (16, 'Charge_Units', 'Typ_Code', 'varchar(10)', 'NO', 'MUL', 'NULL', '', 'Typ_Code', 'CU_Types', 'Typ_Description', 10, 1, 'FK', 'Required()', 'Type');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (17, 'Configuration_Items', 'CC_Id', 'int(11)', 'NO', 'MUL', '0', '', 'CC_Id', 'Cost_Centers', 'CC_Description', 11, 1, 'FK', 'Required()', 'Cost Center Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (18, 'Configuration_Items', 'CIT_Generation', 'int(11)', 'NO', '', '1', '', 'CIT_Generation', 'CIT_Generations', 'Value', 45, 1, 'FK', 'Required()', 'Item Generation Type');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (19, 'Configuration_Items', 'CI_Id', 'int(11)', 'NO', 'PRI', 'NULL', 'auto_increment', 'NULL', 'NULL', 'NULL', 11, 1, 'FK', 'Required()', 'Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (20, 'Configuration_Items', 'CI_Name', 'varchar(45)', 'NO', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Name');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (21, 'Configuration_Items', 'CI_UUID', 'varchar(45)', 'NO', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'UUID');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (22, 'Configuration_Items', 'Cus_Id', 'int(11)', 'NO', 'MUL', '1', '', 'Cus_Id', 'Customers', 'Cus_Name', 11, 1, 'FK', 'Required()', 'Customer Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (23, 'Configuration_Items', 'Pla_Id', 'int(11)', 'NO', 'MUL', '0', '', 'Pla_Id', 'Platforms', 'Pla_Name', 11, 1, 'FK', 'Required()', 'Platform Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (24, 'Cost_Centers', 'CC_Code', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (25, 'Cost_Centers', 'CC_Description', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Description');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (26, 'Cost_Centers', 'CC_Id', 'int(11)', 'NO', 'PRI', 'NULL', 'auto_increment', 'NULL', 'NULL', 'NULL', 11, 1, 'FK', 'Required()', 'Cost Center Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (27, 'Cost_Centers', 'Cur_Code', 'varchar(3)', 'NO', 'MUL', 'NULL', '', 'Cur_Code', 'Currencies', 'Cur_Name', 3, 1, 'FK', 'Required()', 'Currency Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (28, 'Countries', 'Cou_A3', 'varchar(3)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 3, NULL, 'NULL', 'NULL', 'Alphanum Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (29, 'Countries', 'Cou_Code', 'varchar(2)', 'NO', 'PRI', 'NULL', '', 'NULL', 'NULL', 'NULL', 2, 1, 'FK', 'Required()', 'Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (30, 'Countries', 'Cou_N', 'int(11)', 'YES', '', '0', '', 'NULL', 'NULL', 'NULL', 11, NULL, 'NULL', 'NULL', 'ISO Numeric Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (31, 'Countries', 'Cou_Name', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Name');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (32, 'Countries_Currencies', 'Cou_Code', 'varchar(2)', 'NO', 'PRI', 'NULL', '', 'Cou_Code', 'Countries', 'Cou_Name', 2, 1, 'FK', 'Required()', 'Country Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (33, 'Countries_Currencies', 'Cou_Cur_Comment', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Comment');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (34, 'Countries_Currencies', 'Cur_Code', 'varchar(3)', 'NO', 'PRI', 'NULL', '', 'Cur_Code', 'Currencies', 'Cur_Name', 3, 1, 'FK', 'Required()', 'Currency Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (35, 'Currencies', 'Cur_Code', 'varchar(3)', 'NO', 'PRI', 'NULL', '', 'NULL', 'NULL', 'NULL', 3, 1, 'FK', 'Required()', 'Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (36, 'Currencies', 'Cur_Comment', 'varchar(128)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 128, NULL, 'NULL', 'NULL', 'Comment');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (37, 'Currencies', 'Cur_Id', 'int(11)', 'YES', '', '0', '', 'NULL', 'NULL', 'NULL', 11, NULL, 'NULL', 'NULL', 'Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (38, 'Currencies', 'Cur_Name', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Name');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (39, 'Customers', 'CC_Id', 'int(11)', 'NO', 'MUL', '0', '', 'CC_Id', 'Cost_Centers', 'CC_Description', 11, 1, 'FK', 'Required()', 'Cost Center Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (40, 'Customers', 'Cus_Id', 'int(11)', 'NO', 'PRI', 'NULL', 'auto_increment', 'NULL', 'NULL', 'NULL', 11, 1, 'FK', 'Required()', 'Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (41, 'Customers', 'Cus_Name', 'varchar(45)', 'NO', 'UNI', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Name');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (42, 'CU_Types', 'Typ_Code', 'varchar(10)', 'NO', 'PRI', 'NULL', '', 'NULL', 'NULL', 'NULL', 10, 1, 'FK', 'Required()', 'Type');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (43, 'CU_Types', 'Typ_Description', 'varchar(45)', 'NO', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Description');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (44, 'Exchange_Rates', 'Cur_Code', 'varchar(3)', 'NO', 'MUL', 'NULL', '', 'Cur_Code', 'Currencies', 'Cur_Name', 3, 1, 'FK', 'Required()', 'Currency Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (45, 'Exchange_Rates', 'ER_Date', 'date', 'NO', '', '2018-01-01', '', 'NULL', 'NULL', 'NULL', 10, NULL, 'NULL', 'NULL', 'Date');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (46, 'Exchange_Rates', 'ER_Factor', 'decimal(20,6)', 'NO', '', '0.000000', '', 'NULL', 'NULL', 'NULL', 20, NULL, 'NULL', 'NULL', 'Exchange Factor');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (47, 'Exchange_Rates', 'ER_Id', 'int(11)', 'NO', 'PRI', 'NULL', 'auto_increment', 'NULL', 'NULL', 'NULL', 11, 1, 'FK', 'Required()', 'Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (48, 'Measure_Units', 'MU_Code', 'varchar(3)', 'NO', 'PRI', 'NULL', '', 'NULL', 'NULL', 'NULL', 3, 1, 'FK', 'Required()', 'Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (49, 'Measure_Units', 'MU_Description', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Description');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (50, 'Platforms', 'Pla_Host', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Host');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (51, 'Platforms', 'Pla_Id', 'int(11)', 'NO', 'PRI', 'NULL', 'auto_increment', 'NULL', 'NULL', 'NULL', 11, 1, 'FK', 'Required()', 'Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (52, 'Platforms', 'Pla_Name', 'varchar(45)', 'NO', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Name');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (53, 'Platforms', 'Pla_Password', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Password');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (54, 'Platforms', 'Pla_Port', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'Port');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (55, 'Platforms', 'Pla_User', 'varchar(45)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'User');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (56, 'Rates', 'CC_Id', 'int(11)', 'NO', 'MUL', '0', '', 'CC_Id', 'Cost_Centers', 'CC_Description', 11, 1, 'FK', 'Required()', 'Cost Center Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (57, 'Rates', 'Cur_Code', 'varchar(3)', 'NO', 'MUL', 'NULL', '', 'Cur_Code', 'Currencies', 'Cur_Name', 3, 1, 'FK', 'Required()', 'Currency Code');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (58, 'Rates', 'Cus_Id', 'int(11)', 'NO', 'MUL', '0', '', 'Cus_Id', 'Customers', 'Cus_Name', 11, 1, 'FK', 'Required()', 'Customer Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (59, 'Rates', 'CU_Id', 'int(11)', 'NO', 'MUL', '0', '', 'CU_Id', 'Charge_Units', 'CU_Description', 11, 1, 'FK', 'Required()', 'Charge Unit Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (60, 'Rates', 'MU_Code', 'varchar(3)', 'NO', 'MUL', 'NULL', '', 'MU_Code', 'Measure_Units', 'MU_Description', 3, 1, 'FK', 'Required()', 'Measure Unit');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (61, 'Rates', 'Pla_Id', 'int(11)', 'NO', 'MUL', '0', '', 'Pla_Id', 'Platforms', 'Pla_Name', 11, 1, 'FK', 'Required()', 'Platform Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (62, 'Rates', 'Rat_Id', 'int(11)', 'NO', 'PRI', 'NULL', 'auto_increment', 'NULL', 'NULL', 'NULL', 11, 1, 'FK', 'Required()', 'Id');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (63, 'Rates', 'Rat_Period', 'int(11)', 'NO', '', '0', '', 'Rat_Period', 'Rat_Periods', 'Value', 45, 1, 'RF', 'Required()', 'Period');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (64, 'Rates', 'Rat_Price', 'decimal(20,6)', 'YES', '', '0.000000', '', 'NULL', 'NULL', 'NULL', 20, NULL, 'NULL', 'NULL', 'Price');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (65, 'Rates', 'Typ_Code', 'varchar(10)', 'NO', 'MUL', 'NULL', '', 'Typ_Code', 'CU_Types', 'Typ_Description', 10, 1, 'FK', 'Required()', 'Charge Unit Type');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (66, 'Trace', 'ID', 'int(11)', 'NO', 'PRI', 'NULL', 'auto_increment', 'NULL', 'NULL', 'NULL', 11, 1, 'FK', 'Required()', 'ID');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (67, 'Trace', 'LINE', 'varchar(128)', 'YES', '', 'NULL', '', 'NULL', 'NULL', 'NULL', 128, NULL, 'NULL', 'NULL', 'LINE');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (68, 'CIT_Generations', 'CIT_Generation', 'int(11)', 'NO', 'PRI', '0', '', 'NULL', 'NULL', 'NULL', 11, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (69, 'CIT_Generations', 'Value', 'varchar(45)', 'YES', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (70, 'CIT_Statuses', 'CIT_Status', 'int(11)', 'NO', 'PRI', '0', '', 'NULL', 'NULL', 'NULL', 11, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (71, 'CIT_Statuses', 'Value', 'varchar(45)', 'YES', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (72, 'CU_Operations', 'CU_Operation', 'varchar(10)', 'NO', 'PRI', 'NULL', '', 'NULL', 'NULL', 'NULL', 10, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (73, 'CU_Operations', 'Value', 'varchar(45)', 'YES', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (74, 'CU_Operations', 'Is_Multiply', 'tinyint(4)', 'YES', 'NULL', '0', 'NULL', 'NULL', 'NULL', 'NULL', 4, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (75, 'CU_Operations', 'Factor', 'int(11)', 'YES', 'NULL', '0', 'NULL', 'NULL', 'NULL', 'NULL', 11, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (76, 'Rat_Periods', 'Rat_Period', 'int(11)', 'NO', 'PRI', '0', '', 'NULL', 'NULL', 'NULL', 11, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (77, 'Rat_Periods', 'Value', 'varchar(45)', 'YES', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'NULL');
INSERT INTO `collector_development`.`Forms` (`Id`, `Table`, `Field`, `Type`, `Null`, `Key`, `Default`, `Extra`, `Foreign_Key`, `Referenced_Table`, `Foreign_Field`, `Length`, `Validation`, `Validation_Type`, `Validation_String`, `Caption_String`) VALUES (78, 'Countries_Currencies', 'Cou_Cur_Comment', 'varchar(45)', 'YES', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 45, NULL, 'NULL', 'NULL', 'NULL');

COMMIT;


-- -----------------------------------------------------
-- Data for table `collector_development`.`Tables`
-- -----------------------------------------------------
START TRANSACTION;
USE `collector_development`;
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (1, 'Charge_Items', 'Charge Items', 'Charge Item', 'charge_item', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (2, 'Charge_Units', 'Charge Units', 'Charge Unit', 'charge_unit', 'Charge_Items', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (3, 'Configuration_Items', 'Configuration Items', 'Configuration Item', 'configuration_item', 'Charge_Units', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (4, 'Cost_Centers', 'Cost Centers', 'Cost Center', 'cost_center', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (5, 'Countries', 'Countries', 'Country', 'country', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (6, 'Currencies', 'Currencies', 'Currency', 'currency', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (7, 'Customers', 'Customers', 'Customer', 'customer', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (8, 'CU_Types', 'Configuration Unit Types', 'Configuration Unit Type', 'cu_type', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (9, 'Exchange_Rates', 'Exchange Rates', 'Exchange Rate', 'exchange_rate', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (10, 'Measure_Units', 'Measure Units', 'Measure Unit', 'measure_unit', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (11, 'Platforms', 'Platforms', 'Platform', 'platform', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (12, 'Rates', 'Rates', 'Rate', 'rate', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (13, 'Trace', 'Trace', 'Trace line', 'trace', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (14, 'CIT_Generations', 'Configuration Items Generation Types', 'Configuration Item Generation Type', 'cit_generation', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (15, 'CIT_Statuses', 'Configuration Items Status Types', 'Configuration Item Status Type', 'cit_status', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (16, 'CU_Operations', 'Charge Units Conversion Operations', 'Charge Unit Conversion Operation', 'cu_operation', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (17, 'Rat_Periods', 'Rate Periods', 'Rate Period', 'rat_period', 'NULL', 1, 1, 1, 1, 1, 1);
INSERT INTO `collector_development`.`Tables` (`Id`, `Name`, `Caption`, `Entity`, `Class_Name`, `Child_Table`, `Use_Pagination`, `Use_Children_Pagination`, `Generate_Form_One`, `Generate_Form_All`, `Generate_Form_Filter`, `Generate_Children`) VALUES (18, 'Countries_Currencies', 'Countries vs Currencies', 'Country vs Currency', 'country_currency', 'NULL', 1, 1, 1, 1, 1, 1);

COMMIT;

