SUFFIX=$1
echo "ALTER TABLE Charge_Items_${SUFFIX} MODIFY CIT_DateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;"
echo "ALTER TABLE Charge_Items_${SUFFIX} ADD CONSTRAINT pk_Charge_Item_${SUFFIX} PRIMARY KEY (CU_Id,CIT_DateTime);"
echo "ALTER TABLE Charge_Items_${SUFFIX} ADD CONSTRAINT fk_Charge_Item_Charge_Unit1_${SUFFIX} FOREIGN KEY (CU_Id) REFERENCES collector.Charge_Units (CU_Id) ON DELETE NO ACTION ON UPDATE NO ACTION;"
echo "ALTER TABLE Charge_Items_${SUFFIX} ADD CONSTRAINT fk_Charge_Items_CIT_Statuses1_202003 FOREIGN KEY (CIT_Status) REFERENCES collector.CIT_Statuses (CIT_Status) ON DELETE NO ACTION ON UPDATE NO ACTION;"
